### ISSUE TITLE
Importer fichiers rrd vers elasticsearch via beat

### ISSUE THREAD

**Issue by alexisc35** [jlecour/rrdbeat#1]
Bonjour,

J'utilise votre outil rrdbeat dans le but d'importer des données rrd via beats dans ma base elasticsearch. J'utilise un linux Centos7.

Cependant, je rencontre un soucis quand j'exécute la commande de la manière suivante : 

`rrdbeat -c rrdbeat.yml -e mon_fichier.rrd`

J'obtiens le message d'erreur suivant : 

* 2018/05/14 15:34:27.034357 **rrdbeat.go:78: INFO Event sent**
* 2018/05/14 15:34:27.037445 **client.go:452: DBG  ES Ping(url=http://localhost:9200, timeout=1m30s)**
* 2018/05/14 15:34:27.038616 **client.go:461: DBG  Ping status code: 200**
* 2018/05/14 15:34:27.038665 **output.go:159: INFO Trying to load template for client: &{{http://localhost:9200 elasticsearch elasticsearch %!s(http.Client=&{0xc4201aa000 <nil> <nil> 90000000000}) %!s(bool=true) %!s(func() error=0x7369e0)} rrdbeat map[] {{ <nil> %!s(bool=false) %!s(int=0) %!s(int=0) %!s(int=0)}  %!s(elasticsearch.state=0) }}**
* 2018/05/14 15:34:27.039231 **client.go:480: DBG  HEAD http://localhost:9200/_template/rrdbeat <nil>**
* 2018/05/14 15:34:27.039247 **single.go:130: INFO Connecting error publishing events (retrying): Connection marked as failed because the onConnect callback failed: Could not load template: Template could not be loaded. Error: 406 Not Acceptable**
* 2018/05/14 15:34:27.039255 **single.go:145:INFO send fail**

Je voudrais savoir où pointe l'url `http://localhost:9200/_template/rrdbeat`. Si elle apparaît dans le dossier rrdbeat cloné ou dans les répertoires du système ?

**Comment by sigkacey** [comment]
What does your template section look like in rrdbeat.yml?

The 406 probably comes from this beat pre-dating the switch to require application/json header. What version of es are you trying it with?

**Comment by jlecour** [comment]
Hi guys,

Sadly I won't be able to help you.

This code has not been updated for 2 years and even then it was not supposed to work.
It was merely a spike in trying to build a "beat" and it didn't last long.

I'm sorry if this was not clear and if you've spent some time trying to use it.
I'll update the README.
